Edit account
Alex7mob1/SoftServe_CrashCourse_Team1 pull request #1
Opened 2021-04-29 13:39 UTC by rachek-o

2021-04-30 10:38 UTC, adomanich requested changes

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/datamodel/RegisterModel.java
> +
Please, remove extra spaces

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/enums/URLs.java
> +
Please, remove extra spaces

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/EditAccountPage.java
> +    private WebElement dangerMessage;
Try to rewrite it without using "magic numbers" in your locators

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/EditAccountPage.java
> +
Please, remove extra spaces

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/HeaderPage.java
> +    private WebElement loginPageButton;
Please, rename it to loginButton

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/HeaderPage.java
> +
Please, remove extra space

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/LoginPage.java
> +        Thread.sleep(5000);
Using Thread.sleep() is a bad practice, try to replace it with explicit wait

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/LoginPage.java
> +
Please, remove extra space

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/MyAccountPage.java
> +        Thread.sleep(5000);
Using Thread.sleep() is a bad practice, try to replace it with explicit wait

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/MyAccountPage.java
> +
Please, remove extra spaces

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/MyAccountPage.java
> +        Thread.sleep(5000);
Using Thread.sleep() is a bad practice, try to replace it with explicit wait

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/MyAccountPage.java
> +    @FindBy(xpath = ".//div[@class='alert alert-success alert-dismissible']")
you can use xpath - contains() function and define just a part of the full class name in your locator

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/pages/SuccessRegisterPage.java
> +
Please, remove extra space

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/repository/EditAccountModelRepository.java
> +
Please, remove extra space

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/repository/EditAccountModelRepository.java
> +        public static EditAccountModel getEditAccountModel(){
Please, add space here

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/repository/LoginModelRepository.java
> +
Please, remove extra space

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/repository/LoginModelRepository.java
> +    public static LoginModel getLoginModel(){
Please, add space here

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/steps/EditAccountPageBL.java
> +        return this;
I believe it should return new MyAccountPageBL()

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/steps/EditAccountPageBL.java
> +    }
All business logic  methods which are responsible for verifying something should start with "verify" or "check" prefix

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/steps/EditAccountPageBL.java
> +    public void redirectToPreviousPage() throws InterruptedException {
Why do you throw InterruptedException here?

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/steps/HeaderPageBL.java
> +
Please, remove extra spaces

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/steps/HeaderPageBL.java
> +
Please, remove extra space

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/steps/LoginPageBL.java
> +        myAccountPage = new MyAccountPage();
It should be created in constructor within MyAccountPageBL class

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/steps/MyAccountPageBL.java
> +
Please, remove extra space

2021-04-30 10:38 UTC, adomanich commented on src/main/java/com/opencart/steps/MyAccountPageBL.java
> +
Please, remove extra space

2021-04-30 10:38 UTC, adomanich commented on src/test/java/EditAccountTest.java
> +    }
You can perform all negative validations within one test and also, in addition, create a positive one with valid edit data

2021-05-12 17:21 UTC, adomanich approved these changes

2021-05-12 17:24 UTC, Alex7mob1 approved these changes

2021-05-12 17:25 UTC, merged